defaults:
  - model
  - _self_

system:
  save_dir: ./outputs

compress_args:
  scheme: "mix_precision_search"
  targets: ["Linear"]

data:
  num_calibration_samples: 128
  batch_size: 1

  tokenizer_args:
    #tokenizer_path: ${model.model_path}
    use_fast: true
    trust_remote_code: true


